# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52f5ffdcfb40a74589472e42c57d217e17c0068629de6bd030db960c28c0fac2ac793c066991128c343fa963f20ef5a518366624adc154dc45324b74224881eb

test:
  secret_key_base: 326dbb52e900ae27825144fad3233d46f95e17ec1803d82b7f4d8c92cd9daf3089ed55a7ef2f3ca4feec28dbaa148238c057c7310da55847a45d73a42e8dc52f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
